In [17]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

In [18]:
# Loading the dataset
Academic_Success_df = pd.read_csv(r'C:/Intro_DataScience/Week4/Academic_Success_Data.csv')

In [19]:
Academic_Success_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   "Daytime/evening attendance	"                   4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             4424 non-null   int64
 11  Father's occupation                             4424 non-null   int64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   int64
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   object
dtypes: float64(7), int64(29), object(1)
memory usage: 1.2+ MB

In [20]:
Academic_Success_df.head()

,Marital status,Application mode,Application order,Course,"""Daytime/evening attendance\t""",Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [21]:
Academic_Success_df.describe()

,Marital status,Application mode,Application order,Course,"""Daytime/evening attendance\t""",Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
count,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,...,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,1.178571,18.669078,1.727848,8856.642631,0.890823,4.577758,132.613314,1.873192,19.561935,22.275316,...,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,11.566139,1.228029,0.001969
std,0.605747,17.484682,1.313793,2063.566416,0.311897,10.216592,13.188332,6.914514,15.603186,15.343108,...,0.690880,1.918546,2.195951,3.947951,3.014764,5.210808,0.753774,2.663850,1.382711,2.269935
min,1.000000,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,9.400000,0.300000,-1.700000
50%,1.000000,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,1.000000,19.000000,19.000000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,11.100000,1.400000,0.320000
75%,1.000000,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,1.000000,37.000000,37.000000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,13.900000,2.600000,1.790000
max,6.000000,57.000000,9.000000,9991.000000,1.000000,43.000000,190.000000,109.000000,44.000000,44.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000

In [6]:
# Loading and preprocessing the data
def preprocess_data(df):
    # Remove rows where Target is 'Enrolled'
    df = df[df['Target'] != 'Enrolled']
    
    # Convert Target to binary (Dropout = 1, Graduate = 0)
    df['Target'] = (df['Target'] == 'Dropout').astype(int)
    
    # Select numerical columns
    numerical_cols = ['Marital status', 'Application order', 'Previous qualification (grade)', 
                     'Admission grade', 'Age at enrollment', 'Curricular units 1st sem (credited)', 
                     'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)', 
                     'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)', 
                     'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)', 
                     'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)', 
                     'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)', 
                     'Curricular units 2nd sem (without evaluations)', 'Unemployment rate', 
                     'Inflation rate', 'GDP']
    
    return df, numerical_cols

In [7]:
# Function to find optimal threshold
def find_optimal_threshold(y_true, y_pred_proba):
    thresholds = np.arange(0.1, 0.9, 0.05)
    best_threshold = 0.5
    best_f1 = 0
    
    for threshold in thresholds:
        y_pred = (y_pred_proba >= threshold).astype(int)
        current_f1 = f1_score(y_true, y_pred)
        if current_f1 > best_f1:
            best_f1 = current_f1
            best_threshold = threshold
    
    return best_threshold

In [22]:
# Function to evaluate model
def evaluate_model(y_true, y_pred, name):
    print(f"\nResults for {name}")
    print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
    print(f"F1 Score (Dropout): {f1_score(y_true, y_pred):.4f}")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=['Graduate', 'Dropout']))

In [23]:
df, numerical_cols = preprocess_data(Academic_Success_df)

In [24]:
# Prepare features and target
X = Academic_Success_df[numerical_cols]
y = Academic_Success_df['Target']

In [25]:
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [26]:
# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
# Initialize models with class weights
models = {
    'Logistic Regression': LogisticRegression(class_weight=class_weights, max_iter=1000),
    'Random Forest': RandomForestClassifier(class_weight=class_weights, n_estimators=100, random_state=42),
    'XGBoost': XGBClassifier(scale_pos_weight=class_weights[1]/class_weights[0], 
                            eval_metric='logloss', random_state=42)
}

In [28]:
# Train and evaluate models
for name, model in models.items():
    print(f"\nTraining {name}...")
    
    # Train model
    model.fit(X_train_scaled, y_train)
    
    # Get probabilities and optimize threshold
    if hasattr(model, 'predict_proba'):
        y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]
        threshold = find_optimal_threshold(y_test, y_pred_proba)
        y_pred = (y_pred_proba >= threshold).astype(int)
        print(f"Optimal threshold: {threshold:.2f}")
    else:
        y_pred = model.predict(X_test_scaled)
    
    # Evaluate model
    evaluate_model(y_test, y_pred, name)
    
    # Feature importance for Random Forest and XGBoost
    if hasattr(model, 'feature_importances_'):
        importances = pd.DataFrame({
            'feature': numerical_cols,
            'importance': model.feature_importances_
        }).sort_values('importance', ascending=False)
        print(f"\nTop 10 Important Features for {name}:")
        print(importances.head(10))

Training Logistic Regression...

ValueError: The classes, ['Dropout', 'Enrolled', 'Graduate'], are not in class_weight

In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

# Loading and preprocessing the data
def preprocess_data(df):
    # Convert Target to binary (Dropout = 1, Graduate = 0)
    # First remove 'Enrolled' class
    df = df[df['Target'].isin(['Dropout', 'Graduate'])]
    # Then convert to binary
    df['Target'] = (df['Target'] == 'Dropout').astype(int)
    
    # Select numerical columns
    numerical_cols = ['Marital status', 'Application order', 'Previous qualification (grade)', 
                     'Admission grade', 'Age at enrollment', 'Curricular units 1st sem (credited)', 
                     'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)', 
                     'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)', 
                     'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)', 
                     'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)', 
                     'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)', 
                     'Curricular units 2nd sem (without evaluations)', 'Unemployment rate', 
                     'Inflation rate', 'GDP']
    
    return df, numerical_cols

# Function to find optimal threshold
def find_optimal_threshold(y_true, y_pred_proba):
    thresholds = np.arange(0.1, 0.9, 0.05)
    best_threshold = 0.5
    best_f1 = 0
    
    for threshold in thresholds:
        y_pred = (y_pred_proba >= threshold).astype(int)
        current_f1 = f1_score(y_true, y_pred)
        if current_f1 > best_f1:
            best_f1 = current_f1
            best_threshold = threshold
    
    return best_threshold, best_f1

# Function to evaluate model
def evaluate_model(y_true, y_pred, model_name, threshold=None):
    print(f"\nResults for {model_name}")
    if threshold is not None:
        print(f"Optimal threshold: {threshold:.3f}")
    print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
    print(f"F1 Score (Dropout): {f1_score(y_true, y_pred):.4f}")
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=['Graduate', 'Dropout']))

# Load and preprocess the data
print("Loading and preprocessing data...")
Academic_Success_df = pd.read_csv(r'C:/Intro_DataScience/Week4/Academic_Success_Data.csv')
df, numerical_cols = preprocess_data(Academic_Success_df)

# Prepare features and target
X = df[numerical_cols]
y = df['Target']

# Print class distribution
print("\nClass distribution:")
print(df['Target'].value_counts(normalize=True))

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Calculate class weights
class_counts = np.bincount(y_train)
total_samples = len(y_train)
class_weights = {
    0: total_samples / (2 * class_counts[0]),  # weight for Graduate
    1: total_samples / (2 * class_counts[1])   # weight for Dropout
}

print("\nClass weights:")
print(class_weights)

# Initialize models
models = {
    'Logistic Regression': LogisticRegression(
        class_weight=class_weights,
        max_iter=1000,
        random_state=42
    ),
    'Random Forest': RandomForestClassifier(
        class_weight=class_weights,
        n_estimators=100,
        random_state=42
    ),
    'XGBoost': XGBClassifier(
        scale_pos_weight=class_weights[1]/class_weights[0],
        eval_metric='logloss',
        random_state=42
    )
}

# Train and evaluate models
results = {}
for name, model in models.items():
    print(f"\nTraining {name}...")
    
    # Train model
    model.fit(X_train_scaled, y_train)
    
    # Get predictions
    if hasattr(model, 'predict_proba'):
        y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]
        threshold, best_f1 = find_optimal_threshold(y_test, y_pred_proba)
        y_pred = (y_pred_proba >= threshold).astype(int)
        evaluate_model(y_test, y_pred, name, threshold)
    else:
        y_pred = model.predict(X_test_scaled)
        evaluate_model(y_test, y_pred, name)
    
    # Feature importance for Random Forest and XGBoost
    if hasattr(model, 'feature_importances_'):
        importances = pd.DataFrame({
            'feature': numerical_cols,
            'importance': model.feature_importances_
        }).sort_values('importance', ascending=False)
        print(f"\nTop 10 Important Features for {name}:")
        print(importances.head(10))

# Print overall summary
print("\nOverall Summary:")
for name in models.keys():
    f1 = f1_score(y_test, y_pred)
    acc = accuracy_score(y_test, y_pred)
    print(f"{name}: F1={f1:.4f}, Accuracy={acc:.4f}")

Loading and preprocessing data...

Class distribution:
Target
0    0.60854
1    0.39146
Name: proportion, dtype: float64

Class weights:
{0: 0.8217981888745148, 1: 1.2768844221105529}

Training Logistic Regression...

C:\Users\ashir\AppData\Local\Temp\ipykernel_45104\1505753831.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Target'] = (df['Target'] == 'Dropout').astype(int)

Results for Logistic Regression
Optimal threshold: 0.650
Accuracy: 0.9137
F1 Score (Dropout): 0.8848

Confusion Matrix:
[[634  29]
 [ 65 361]]

Classification Report:
              precision    recall  f1-score   support

    Graduate       0.91      0.96      0.93       663
     Dropout       0.93      0.85      0.88       426

    accuracy                           0.91      1089
   macro avg       0.92      0.90      0.91      1089
weighted avg       0.91      0.91      0.91      1089


Training Random Forest...

Results for Random Forest
Optimal threshold: 0.350
Accuracy: 0.8953
F1 Score (Dropout): 0.8705

Confusion Matrix:
[[592  71]
 [ 43 383]]

Classification Report:
              precision    recall  f1-score   support

    Graduate       0.93      0.89      0.91       663
     Dropout       0.84      0.90      0.87       426

    accuracy                           0.90      1089
   macro avg       0.89      0.90      0.89      1089
weighted avg       0.90      0.90      0.90      1089


Top 10 Important Features for Random Forest:
                                   feature  importance
14     Curricular units 2nd sem (approved)    0.228279
15        Curricular units 2nd sem (grade)    0.166747
8      Curricular units 1st sem (approved)    0.138480
9         Curricular units 1st sem (grade)    0.079583
3                          Admission grade    0.051795
4                        Age at enrollment    0.051737
2           Previous qualification (grade)    0.045729
13  Curricular units 2nd sem (evaluations)    0.040201
7   Curricular units 1st sem (evaluations)    0.038725
6      Curricular units 1st sem (enrolled)    0.023051

Training XGBoost...

Results for XGBoost
Optimal threshold: 0.750
Accuracy: 0.9045
F1 Score (Dropout): 0.8716

Confusion Matrix:
[[632  31]
 [ 73 353]]

Classification Report:
              precision    recall  f1-score   support

    Graduate       0.90      0.95      0.92       663
     Dropout       0.92      0.83      0.87       426

    accuracy                           0.90      1089
   macro avg       0.91      0.89      0.90      1089
weighted avg       0.91      0.90      0.90      1089


Top 10 Important Features for XGBoost:
                                           feature  importance
14             Curricular units 2nd sem (approved)    0.435805
6              Curricular units 1st sem (enrolled)    0.073743
11             Curricular units 2nd sem (credited)    0.049212
16  Curricular units 2nd sem (without evaluations)    0.048552
10  Curricular units 1st sem (without evaluations)    0.041239
8              Curricular units 1st sem (approved)    0.032829
0                                   Marital status    0.032653
12             Curricular units 2nd sem (enrolled)    0.032370
4                                Age at enrollment    0.025480
15                Curricular units 2nd sem (grade)    0.025209

Overall Summary:
Logistic Regression: F1=0.8716, Accuracy=0.9045
Random Forest: F1=0.8716, Accuracy=0.9045
XGBoost: F1=0.8716, Accuracy=0.9045